/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SklepyRouteImport } from './routes/sklepy'
import { Route as PromocjeRouteImport } from './routes/promocje'
import { Route as PawilonyRouteImport } from './routes/pawilony'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const SklepyRoute = SklepyRouteImport.update({
  id: '/sklepy',
  path: '/sklepy',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocjeRoute = PromocjeRouteImport.update({
  id: '/promocje',
  path: '/promocje',
  getParentRoute: () => rootRouteImport,
} as any)
const PawilonyRoute = PawilonyRouteImport.update({
  id: '/pawilony',
  path: '/pawilony',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/pawilony': typeof PawilonyRoute
  '/promocje': typeof PromocjeRoute
  '/sklepy': typeof SklepyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/pawilony': typeof PawilonyRoute
  '/promocje': typeof PromocjeRoute
  '/sklepy': typeof SklepyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/pawilony': typeof PawilonyRoute
  '/promocje': typeof PromocjeRoute
  '/sklepy': typeof SklepyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/pawilony' | '/promocje' | '/sklepy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/pawilony' | '/promocje' | '/sklepy'
  id: '__root__' | '/' | '/kontakt' | '/pawilony' | '/promocje' | '/sklepy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PawilonyRoute: typeof PawilonyRoute
  PromocjeRoute: typeof PromocjeRoute
  SklepyRoute: typeof SklepyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sklepy': {
      id: '/sklepy'
      path: '/sklepy'
      fullPath: '/sklepy'
      preLoaderRoute: typeof SklepyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocje': {
      id: '/promocje'
      path: '/promocje'
      fullPath: '/promocje'
      preLoaderRoute: typeof PromocjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pawilony': {
      id: '/pawilony'
      path: '/pawilony'
      fullPath: '/pawilony'
      preLoaderRoute: typeof PawilonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PawilonyRoute: PawilonyRoute,
  PromocjeRoute: PromocjeRoute,
  SklepyRoute: SklepyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
